displayName=Uncharged Jewellery reminder
author=Fjoes
description=This plugin warns you when you enter the wilderness with an uncharged glory, ring of wealth, and/or combat bracelet.
tags=wilderness,glory,ring of wealth,combat bracelet,pvp
version=1.0
plugins=com.UnchargedJewelleryReminder.UnchargedJewelleryReminderPlugin
build=standard
